//
//  ContentView.swift
//  App (Generated by SwiftyLaunch 2.0)
//  https://docs.swiftylaun.ch/module/app
//

import FirebaseKit
import InAppPurchaseKit
import NotifKit
import SharedKit
import SwiftUI

struct ContentView: View {

    @EnvironmentObject var db: DB
    
	init() {
		// Make NavigationTitle Rounded

		// Large NavigationTitle
		var roundedLargeTitleFont = UIFont.preferredFont(forTextStyle: .largeTitle)
		roundedLargeTitleFont = UIFont(
			descriptor:
				roundedLargeTitleFont.fontDescriptor
				.withDesign(.rounded)?
				.withSymbolicTraits(.traitBold)
				?? roundedLargeTitleFont.fontDescriptor,
			size: roundedLargeTitleFont.pointSize
		)
		UINavigationBar.appearance().largeTitleTextAttributes = [.font: roundedLargeTitleFont]

		// Small NavigationTitle
		var roundedHeadlineFont = UIFont.preferredFont(forTextStyle: .headline)
		roundedHeadlineFont = UIFont(
			descriptor:
				roundedHeadlineFont.fontDescriptor
				.withDesign(.rounded)?
				.withSymbolicTraits(.traitBold)
				?? roundedHeadlineFont.fontDescriptor,
			size: roundedHeadlineFont.pointSize
		)
		UINavigationBar.appearance().titleTextAttributes = [.font: roundedHeadlineFont]

		// Make TabBar Text Rounded
		var roundedCaptionFont = UIFont.preferredFont(forTextStyle: .caption2)
		roundedCaptionFont = UIFont(
			descriptor:
				roundedCaptionFont.fontDescriptor
				.withDesign(.rounded)?
				.withSymbolicTraits(.traitBold)
				?? roundedCaptionFont.fontDescriptor,
			size: roundedCaptionFont.pointSize
		)
		UITabBarItem.appearance().setTitleTextAttributes([.font: roundedCaptionFont], for: .normal)

	}

	var body: some View {
		TabView {

			// View with AdsKit Examples.
//			Tab("AdsKit Exmpls.", systemImage: "rectangle.3.group.fill") {
//				AdsKitExamples()
//			}
            Tab("Home", systemImage: "house.fill") {
                StoryGeneratorView().requireLogin(db: db, navTitle: "Sign in to Continue", onCancel: {
                        print("User not logged in")
                })
            }
            
            Tab("History", systemImage: "clock.fill") {
                SavedStoryListView(savedStories: StoryGenerator.shared.savedStories()).requireLogin(db: db, navTitle: "Sign in to Continue", onCancel: {
                    print("User not logged in")
            })
            }
			// Example view on how to access the Database.
//			Tab("Sample Story", systemImage: "externaldrive.badge.icloud") {
//				DatabaseExampleView()
//			}

			// Pre-made Settings View for easy native-looking settings screen.
			Tab("Settings", systemImage: "gear") {
				SettingsView()
			}

			#if DEBUG

				TabSection("DEBUG ONLY") {
					// Use this to create quick settings and toggles to streamline the development process
					Tab("Developer", systemImage: "hammer") {
						DeveloperSettingsView()
					}
				}

			#endif
		}

		.tabViewStyle(.sidebarAdaptable)
		.tabViewSidebarHeader {
			Text("SwiftyLaunch App")
				.font(.title)
				.bold()
				.frame(maxWidth: .infinity, alignment: .leading)

		}

	}
}

#Preview {
	ContentView()
		.environmentObject(DB())
		.environmentObject(InAppPurchases())
}
